apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-ms-config
  namespace: payment-ms
data:
  ASPNETCORE_URLS: "http://+:5000"
  ASPNETCORE_ENVIRONMENT: "Development"
  
  APP_URL: "https://localhost:8083"

  # Mercado Pago
  MERCADO_PAGO_SPONSOR_ID: "662208785"
  MERCADO_PAGO_BASE_URL: "https://api.mercadopago.com"
  MERCADO_PAGO_PAGAMENTO_QRCODE_CONTROLLER: "instore/orders/qr/seller/collectors"
  MERCADO_PAGO_USER_ID: "2439756402"
  MERCADO_PAGO_EXTERNAL_POS_ID: "SUC001POS001"


