apiVersion: v1
kind: Secret
metadata:
  name: fastfood-secret
type: Opaque
stringData:
 
  SQL_PASSWORD: Your_password123

  # Banco de Dados

  # Esta é a string de conexão para o banco de dados principal
  DEFAULT_CONNECTION_STRING: "Server=sqlserver;Database=FastFoodChallenge;User=sa;Password=Your_password123;TrustServerCertificate=True"
  
  # Esta é a string de conexão para o banco de dados "master" para operações administrativas
  MASTER_CONNECTION_STRING: "Server=sqlserver;Database=master;User=sa;Password=Your_password123;TrustServerCertificate=True"

  # Mercado Pago
  MERCADO_PAGO_ACCESS_TOKEN: APP_USR-5348444362605432-051315-09269985b96678460c4867c15140cf55-2439756402

  # Email
  EMAIL_PASSWORD: sxrs rsip ydzk tuaj

  # Autenticação nas APIs
  API_AUTH_TOKEN: Yf29qN58VfWbT1YtZz7jRkE4sLt9xP2eUqK3LmXvHsDcMgAjBwNvZxQrFtGvKyLz

