apiVersion: v1
kind: Secret
metadata:
  name: payment-ms-secret
  namespace: payment-ms
type: Opaque
stringData:
 
  # Esta é a string de conexão para o banco de dados
  DB_CONNECTION_STRING: >
    Server=goncalvesc97-fiap-tc-4-login-ms-db.c6nwqiks6njl.us-east-1.rds.amazonaws.com,1433;
    Database=PaymentDb;
    User Id=admin;
    Password=1q2w3e4r5t;
    Encrypt=True;
    TrustServerCertificate=True;

  # Nome do database
  DB_NAME: "PaymentDb"

  # Mercado Pago
  MERCADO_PAGO_ACCESS_TOKEN: APP_USR-5348444362605432-051315-09269985b96678460c4867c15140cf55-2439756402

  # Autenticação nas APIs
  API_AUTH_TOKEN: Yf29qN58VfWbT1YtZz7jRkE4sLt9xP2eUqK3LmXvHsDcMgAjBwNvZxQrFtGvKyLz

