apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-ms-webapi-deployment
  namespace: payment-ms
  labels:
    app: payment-ms-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-ms-webapi
  template:
    metadata:
      labels:
        app: payment-ms-webapi
    spec:
      containers:
      - name: payment-ms-webapi
        image: goncalvesc97/fiap-tc-4-payment-ms:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"

        # Configuração do ambiente de banco de dados 

        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: payment-ms-secret
              key: DB_CONNECTION_STRING

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: payment-ms-secret
              key: DB_NAME

        # Configuração da chave de autenticação da API

        - name: API_AUTHENTICATION_KEY
          valueFrom:
            secretKeyRef:
              name: payment-ms-secret
              key: API_AUTH_TOKEN

        # Configuração dos caminhos de microsserviços

        - name: APP_SETTINGS__AppUrl
          valueFrom:
            configMapKeyRef:
              name: payment-ms-config
              key: APP_URL

        - name: ORDER_MS_URL
          valueFrom:
            configMapKeyRef:
              name: payment-ms-config
              key: ORDER_MS_URL

        # Configuração do Mercado Pago

        - name: PAYMENT_SETTINGS__SponsorId
          valueFrom:
            configMapKeyRef:
              name: payment-ms-config
              key: MERCADO_PAGO_SPONSOR_ID

        - name: PAYMENT_SETTINGS__BaseUrl
          valueFrom:
            configMapKeyRef:
              name: payment-ms-config
              key: MERCADO_PAGO_BASE_URL

        - name: PAYMENT_SETTINGS__PaymentController
          valueFrom:
            configMapKeyRef:
              name: payment-ms-config
              key: MERCADO_PAGO_PAGAMENTO_QRCODE_CONTROLLER

        - name: PAYMENT_SETTINGS__UserId
          valueFrom:
            configMapKeyRef:
              name: payment-ms-config
              key: MERCADO_PAGO_USER_ID

        - name: PAYMENT_SETTINGS__ExternalPosId
          valueFrom:
            configMapKeyRef:
              name: payment-ms-config
              key: MERCADO_PAGO_EXTERNAL_POS_ID

        - name: PAYMENT_SETTINGS__Token
          valueFrom:
            secretKeyRef:
              name: payment-ms-secret
              key: MERCADO_PAGO_ACCESS_TOKEN