apiVersion: v1
kind: Service
metadata:
  name: payment-ms-webapi-service
  namespace: payment-ms
spec:
  type: LoadBalancer
  selector:
    app: payment-ms-webapi
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 5000